  card({
    id: 'bash-punch',
    name: 'BASH Punch',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Multi'],
    packRestrictions: {'female': 'forbidden'},
    fortitude: 4,
    damage: 8,
    text: 'Cannot be packed by Female Superstars.',
    set: 'Extras',
  }),
  card({
    id: 'rolling-neck-breaker',
    name: 'Rolling Neck Breaker',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    extraTypes: ['Reversal'],
    traits: ['Special'],
    fortitude: 5,
    damage: 8,
    text: "Cannot be reversed by hybrid Reversal cards. As a reversal, reverse any card with the word "Dynamic" in the title and end your opponent's turn.",
    reverses: {"cardTitles": ["Dynamic"]},
    reversalFromHandOnly: true,
    set: 'Extras',
  }),
  card({
    id: 'stretch-opponent',
    name: 'Stretch Opponent',
    type: 'Maneuver',
    subtypes: ['Submission'],
    traits: ['Chain'],
    fortitude: 10,
    damage: 8,
    text: 'When successfully played, put up to 2 Action: Chain cards from your Ringside pile into your hand.',
    set: 'Extras',
  }),
  card({
    id: 'shoot-lock-up',
    name: 'Shoot Lock-up',
    type: 'Maneuver',
    subtypes: ['Submission'],
    traits: ['Multi'],
    packRestrictions: {'female': 'forbidden'},
    fortitude: 9,
    damage: 8,
    text: 'Cannot be packed by Female Superstars. When your opponent is a GM or Legend Superstar, this card is -9F. When your Fortitude Rating is at least 5 less than his Fortitude Rating, this card can only be reversed from his Arsenal.',
    set: 'Extras',
  }),
  card({
    id: 'fujiwara-arm-bar',
    name: 'Fujiwara Arm Bar',
    type: 'Maneuver',
    subtypes: ['Submission'],
    traits: ['Chain', 'Cheater'],
    fortitude: 12,
    damage: 13,
    text: 'Can only be played after a successfully played card. When successfully played, you may put 1 card from your Ringside pile into your hand.',
    set: 'Extras',
  }),
  card({
    id: 'precision-suplex',
    name: 'Precision Suplex',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    fortitude: 20,
    damage: 20,
    text: 'When played, name a number 5 or less. Your opponent shuffles that many of his cards that have been removed from the game into his Arsenal. This card is -2F for each number named.',
    set: 'Extras',
  }),
  card({
    id: 'quick-snap-suplex',
    name: 'Quick Snap Suplex',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    traits: ['Heat'],
    fortitude: 7,
    damage: 8,
    text: 'When successfully played, choose 1: remove any number of Heat cards in your Ringside pile from the game and then search your Arsenal for the same number of Heat cards, put them into your Ringside pile, and shuffle your Arsenal; or discard any number of Heat cards and then search your Arsenal for the same number of Heat cards, remove them from the game, and shuffle your Arsenal.',
    set: 'Extras',
  }),
  card({
    id: 'bash-headlock',
    name: 'BASH Headlock',
    type: 'Maneuver',
    subtypes: ['Submission'],
    traits: ['Multi'],
    packRestrictions: {'female': 'forbidden'},
    fortitude: 2,
    damage: 6,
    text: 'Cannot be packed by Female Superstars. When successfully played, your opponent discards 1 card.',
    set: 'Extras',
  }),
  card({
    id: 'the-power-is-back',
    name: 'The Power Is Back',
    type: 'Action',
    fortitude: 0,
    damage: 0,
    text: "Draw 1 card. Your cards are -5F for the rest of this turn and during your opponent's next turn.",
    set: 'Extras',
  }),
  card({
    id: 'listen-loud-and-clear',
    name: 'Listen Loud and Clear',
    type: 'Action',
    fortitude: 3,
    damage: 0,
    text: 'Draw 1 card and your next card played this turn is -7F.',
    set: 'Extras',
  }),
  card({
    id: 'headlock-takedown',
    name: 'Headlock Takedown',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    traits: ['Throwback', 'Ace'],
    fortitude: 0,
    damage: 1,
    text: 'When this card is in your Ring area, during your turn you may put this card into your Ringside pile and if your next card played this turn is a non-unique card, it is -10F.',
    set: 'Extras',
  }),
  card({
    id: 'no-pain-no-chain',
    name: 'No Pain, No Chain',
    type: 'Action',
    traits: ['Chain'],
    fortitude: 3,
    damage: 0,
    text: 'Draw 3 cards, shuffle 3 cards from your Ringside pile into your Arsenal, and then discard 3 cards. When your next card played this turn is the card titled Chained Aggression, it cannot be reversed.',
    set: 'Extras',
  }),
  card({
    id: 'precision-figure-four',
    name: 'Precision Figure Four',
    type: 'Maneuver',
    subtypes: ['Submission'],
    fortitude: 14,
    damage: 16,
    notes: 'rare',
    text: 'When played, shuffle up to 5 cards from your hand into your Arsenal. This card is -2F for each card shuffled in.',
    set: 'Extras',
  }),
  card({
    id: 'fisticuffs',
    name: 'Fisticuffs',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Volley'],
    fortitude: 5,
    damage: 9,
    notes: 'rare',
    text: "When this card is reversed from your opponent's hand, remove 4 cards in his Ringside pile from the game.",
    set: 'Extras',
  }),
  card({
    id: 'give-and-take',
    name: 'Give & Take',
    type: 'Action',
    traits: ['Throwback', 'Fan Favorite!'],
    fortitude: 0,
    damage: 0,
    text: 'All players may put 2 cards from their Ringside pile on the bottom of their Arsenal. When this card is in your Ring area, whenever your opponent successfully plays a card that allows him to search his Arsenal for any number of cards, you may search your Arsenal for 1 non-unique card, reveal it to him, put it into your hand, and shuffle your Arsenal.',
    set: 'Extras',
  }),
  card({
    id: 'kidney-punch',
    name: 'Kidney Punch',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Volley'],
    fortitude: 4,
    damage: 8,
    notes: 'rare',
    text: 'When this card is in your Ringside pile, during your turn you may remove 4 cards in your Ringside pile from the game and then put this card into your hand.',
    set: 'Extras',
  }),
  card({
    id: 'knee-breaker',
    name: 'Knee Breaker',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Throwback'],
    fortitude: 1,
    damage: 8,
    text: "Can only be played after a successfully played card or if you reversed a card to end your opponent's last turn and this is the first card played of your turn. When this card is in your Ring area, your cards with the word "leg" in the title are +1D.",
    set: 'Extras',
  }),
  card({
    id: 'back-fist',
    name: 'Back Fist',
    type: 'Maneuver',
    subtypes: ['Strike'],
    extraTypes: ['Reversal'],
    traits: ['Volley', 'Special'],
    fortitude: 6,
    damage: 4,
    notes: 'rare',
    text: "As a maneuver, this card is -6F and when this is the first card played of your turn, it is also +4D. As a reversal, reverse any maneuver of 3D or less and end your opponent's turn.",
    reverses: {"maxDamage": 3},
    reversalFromHandOnly: true,
    set: 'Extras',
  }),
  card({
    id: 'wrist-breaker',
    name: 'Wrist Breaker',
    type: 'Maneuver',
    subtypes: ['Submission'],
    fortitude: 2,
    damage: 6,
    text: "When successfully played, you may look at your opponent's hand or Backlash deck.",
    set: 'Extras',
  }),
  card({
    id: 'standing-drop-kick',
    name: 'Standing Drop Kick',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Throwback'],
    fortitude: 8,
    damage: 8,
    text: "This card is -3F when your Fortitude Rating is less than your opponent's Fortitude Rating. When successfully played, your opponent discards 3 cards.",
    set: 'Extras',
  }),
  card({
    id: 'stagger',
    name: 'Stagger',
    type: 'Action',
    traits: ['Throwback'],
    fortitude: 3,
    damage: 0,
    text: 'Can only be played after a successfully played maneuver. Draw 1 card. When your next card played this turn is a maneuver of 9D or less, it cannot be reversed.',
    set: 'Extras',
  }),
  card({
    id: 'running-spinebuster',
    name: 'Running Spinebuster',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    traits: ['Throwback', 'Ace'],
    fortitude: 4,
    damage: 7,
    text: 'When this card is in your Ring area, during your turn you may put this card into your Ringside pile and then shuffle up to 2 other cards from your Ringside pile into your Arsenal.',
    set: 'Extras',
  }),
  card({
    id: 'pendulum-back-breaker',
    name: 'Pendulum Back Breaker',
    type: 'Maneuver',
    subtypes: ['Grapple'],
    traits: ['Chain'],
    fortitude: 9,
    damage: 9,
    text: "When your Fortitude Rating is less than your opponent's Fortitude Rating, this card is -5F.",
    set: 'Extras',
  }),
  card({
    id: 'not-yet',
    name: 'Not Yet',
    type: 'Action',
    traits: ['Face', 'Throwback'],
    fortitude: 0,
    damage: 0,
    text: 'Put 1 card from your hand on the bottom of your Arsenal and then look at the top 10 cards of your Arsenal, put 2 into your hand, and put the rest on the bottom of your Arsenal.',
    set: 'Extras',
  }),
  card({
    id: '360-degree-clothesline',
    name: '360-Degree Clothesline',
    type: 'Maneuver',
    subtypes: ['Strike'],
    extraTypes: ['Reversal'],
    traits: ['Special', 'Survivor Series'],
    fortitude: 12,
    damage: 10,
    text: "As a reversal, reverse any maneuver with the word "kick" in the title and end your opponent's turn. When successfully played, shuffle up to 3 cards from your Ringside pile into your Arsenal.",
    reverses: {"cardTitles": ["kick"]},
    reversalFromHandOnly: true,
    set: 'Extras',
  }),
  card({
    id: 'great-technical-knowledge',
    name: 'Great Technical Knowledge',
    type: 'Action',
    traits: ['Throwback', 'Survivor Series'],
    fortitude: 0,
    damage: 0,
    text: 'Draw 1 card. When this card is in your Ring area, your Submission maneuvers are +1D.',
    set: 'Extras',
  }),
  card({
    id: 'dont-cross-the-boss',
    name: 'Don't Cross the Boss',
    type: 'Action',
    traits: ['Throwback', 'Survivor Series'],
    fortitude: 6,
    damage: 0,
    text: 'When this card is in your Ring area, if your opponent successfully plays an Action card, you may draw 1 card.',
    set: 'Extras',
  }),