  card({
    id: 'dirty-low-blow',
    name: 'Dirty Low Blow',
    type: 'Maneuver',
    subtypes: ['Strike'],
    traits: ['Heel'],
    fortitude: 0,
    damage: 2,
    text: "Can only be played when your Fortitude Rating is less than your opponent's Fortitude Rating. Cannot be reversed from your opponent's hand.",,
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),
  card({
    id: 'backlash-card',
    name: 'Backlash!',
    type: 'Reversal',
    traits: ['Special'],
    fortitude: 0,
    damage: 3,
    text: "Can only be played if your Fortitude Rating is less than your opponent's Fortitude Rating. Reverse any Strike, Grapple, or Submission maneuver if it is not the first maneuver played this turn and end your opponent's turn.",,
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),
  card({
    id: 'chain-barrier',
    name: 'Chain Barrier',
    type: 'Action',
    extraTypes: ['Action'],
    traits: ['Multi', 'Active'],
    fortitude: 0,
    damage: 0,
    text: 'When this card is in your Ring area, discard 1 card fewer in order to be able to reverse a Chain card from your hand or Backlash deck.',
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),
  card({
    id: 'tormented-tomfoolery',
    name: 'Tormented Tomfoolery',
    type: 'Maneuver',
    subtypes: ['Grapple', 'Submission'],
    traits: ['Fan Favorite!'],
    fortitude: 4,
    damage: 6,
    text: 'When played, choose Grapple or Submission. This card is considered to be only the chosen type. When successfully played, your next card played this turn is -15F.',
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),
  card({
    id: 'precision-personified',
    name: 'Precision Personified',
    type: 'Action',
    traits: ['Fan Favorite!'],
    fortitude: 0,
    damage: 0,
    text: 'Search your Arsenal for 1 card with the word "precision" in the title, reveal it to your opponent, put it into your hand, and shuffle your Arsenal.',
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),
  card({
    id: 'backfire',
    name: 'Backfire',
    type: 'Action',
    traits: ['Heat'],
    fortitude: 4,
    damage: 0,
    text: "Cannot be reversed from your opponent's hand if you have Heat cards in your Ring area. Look at your opponent's hand. He overturns cards equal to the number of Reversal cards in his hand and in his Ring area.",,
    backlash: 'Mid-match',
    set: 'Midmatch',
  }),